
server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        provider:
          okta:
            issuer-uri: ${OKTA_APP_ISSUER}
        registration:
          okta:
            client-id: ${OKTA_APP_CLIENT_ID}
            client-secret: ${OKTA_APP_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: openid
      resourceserver:
        jwt:
          issuer-uri: ${OKTA_APP_ISSUER}

